name: voetdeluxe
trigger:
  branches:
    include:
    - main
variables:
  buildConfiguration: 'Release'
  containerRegistry: 'Azure Container Registry VoetDeluxe'
  imageName: 'vdlx-front'
  version: '1.0'
  tag: '$(Build.BuildId)'
pool:
  vmImage: 'ubuntu-latest'
stages:
# Build stage
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '15.x'
        checkLatest: true
    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
    - task: Docker@2
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(version)
# Deploy stage
- stage: DeployVM
  jobs:
  - deployment: Production
    displayName: Deploy Containers
    environment: 'JustClouds VM.HomeVM'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: "docker network ls"
          - script: "hostname"
          - task: DockerCompose@0
            displayName: Pull updated images
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'Moerman Azure (04ddb791-10a0-45f8-b666-8b57cfb65a1c)'
              azureContainerRegistry: '{"loginServer":"acrvoetdeluxe.azurecr.io", "id" : "/subscriptions/04ddb791-10a0-45f8-b666-8b57cfb65a1c/resourceGroups/voetdeluxe-rg/providers/Microsoft.ContainerRegistry/registries/acrvoetdeluxe"}'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose Pull command'
              dockerComposeCommand: 'pull'
          - task: DockerCompose@0
            displayName: Deploy to VM with Docker Compose
            inputs:
              containerregistrytype: 'Azure Container Registry'
              azureSubscription: 'Moerman Azure (04ddb791-10a0-45f8-b666-8b57cfb65a1c)'
              azureContainerRegistry: '{"loginServer":"acrvoetdeluxe.azurecr.io", "id" : "/subscriptions/04ddb791-10a0-45f8-b666-8b57cfb65a1c/resourceGroups/voetdeluxe-rg/providers/Microsoft.ContainerRegistry/registries/acrvoetdeluxe"}'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'up'
              arguments: '-d'
