name: voetdeluxe
trigger:
  branches:
    include:
    - main
variables:
  buildConfiguration: 'Release'
  containerRegistry: 'Docker Hub'
  imageName: 'voetdeluxe'
  version: '1.0'
  tag: '$(Build.BuildId)'
pool:
  vmImage: 'ubuntu-latest'
# Build stage
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: DockerImage
    displayName: Build and push Docker image
    steps:
    - task: Docker@1
      displayName: 'Build the Docker image'
      inputs:
        containerregistrytype: 'Container Registry'
        dockerRegistryEndpoint: '$(containerRegistry)'
        command: 'Build an image'
        dockerFile: '**/Dockerfile'
        imageName: '$(imageName)'
        includeLatestTag: true
        useDefaultContext: false
        buildContext: '.'


    - task: Docker@2
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(version)
