# Docker
# Build and push VoetDeluxe Nuxt.js website image to Docker Hub

name: voetdeluxe

trigger:
  branches:
    include:
    - main

resources:
- repo: self

variables:
  buildConfiguration: 'Release'
  imageName: 'crazyelectron/voetdeluxe'
  dockerFile: '**/Dockerfile'
  version: '1.0.0'
  tag: 'azuredevops-$(Build.BuildId)'

stages:

# --- Build and Push stage
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'build'
        dockerFile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/'
        tags: '$(tag)'
    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'push'
        tags: '$(tag)'
