name: voetdeluxe
trigger:
  branches:
    include:
    - main
variables:
  buildConfiguration: 'Release'
  containerRegistry: 'Azure Container Registry VoetDeluxe'
  imageName: 'voetdeluxe'
  version: '1.0'
  tag: '$(Build.BuildId)'
pool:
  vmImage: 'ubuntu-latest'
stages:
# Build stage
- stage: Build
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '15.x'
        checkLatest: true
    - script: |
        npm install
        npm run build --if-present
        npm run test --if-present
      displayName: 'npm install, build and test'
    - task: Docker@2
      inputs:
        containerRegistry: '$(containerRegistry)'
        repository: '$(imageName)'
        command: buildAndPush
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(version)
