# Docker
# Build and push VoetDeluxe Nuxt.js website image to Docker Hub

name: voetdeluxe

trigger:
  branches:
    include:
    - main

resources:
- repo: self

variables:
  buildConfiguration: 'Release'
  imageName: 'crazyelectron/voetdeluxe'
  dockerFile: '**/Dockerfile'
  version: '1.0.0'
  tag: 'azuredevops-$(Build.BuildId)'

stages:

# --- Build and Push stage
- stage: Build
  displayName: Build and Push image
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'build'
        dockerFile: '**/Dockerfile'
        buildContext: '$(Build.SourcesDirectory)/'
        tags: '$(tag)'
    - task: Docker@2
      displayName: 'Push the Docker image to Dockerhub'
      inputs:
        containerRegistry: 'Docker Hub'
        repository: '$(imageName)'
        command: 'push'
        tags: '$(tag)'

# --- Deploy stage
- stage: DeployVM
  jobs:
  - deployment: VMDeploy
    displayName: Deploy Containers
    environment:
      name:  'voetdeluxehomevm'
      resourceType: VirtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - script: "docker network ls"
          - script: "hostname"
          - task: DockerCompose@0
            displayName: Pull updated images
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'pull'
          - task: DockerCompose@0
            displayName: Deploy to VM with Docker Compose
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'Docker Hub'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Run a Docker Compose command'
              dockerComposeCommand: 'up'
              arguments: '-d'
