---
version: "3.5"

services:

  voetdeluxe:
    build:
      context: .
      dockerfile: Dockerfile
    image: crazyelectron/voetdeluxe:latest
    container_name: voetdeluxe
    networks:
      - traefik-network
    ports:
      - "3000:3000"
    environment:
      - PUID=1001
      - GUID=1002
      - GOOGLE_ANALYTICS_ID
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voetdeluxe.rule=Host(`www.voetdeluxe.nl`, `voetdeluxe.nl`)"
      - "traefik.http.routers.voetdeluxe.entryPoints=secure"
      - "traefik.http.routers.voetdeluxe.tls.certresolver=le"
    command: "npm run start"

networks:
  traefik-network:
    external: true
    # driver: bridge
