---
version: "3.5"

services:

  voetdeluxe:
    build:
      context: .
      dockerfile: Dockerfile
    image: voetdeluxe:1.0.2
    container_name: voetdeluxe
    networks:
      - traefik-network
    ports:
      - "6800:6800"
    environment:
      - PUID=1001
      - GUID=1002
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voetdeluxe.rule=Host(`www.voetdeluxe.nl`, `voetdeluxe.nl`)"
      - "traefik.http.routers.voetdeluxe.entryPoints=secure"
      - "traefik.http.routers.voetdeluxe.tls.certresolver=le"
    command: "npm run start"

networks:
  traefik-network:
    external: true
    # driver: bridge
